version: '3'
services:
  cache-api:
    container_name: cache-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      SERVICE_NAME: 'cache-api'
      HOST: '0.0.0.0'
      PORT: '8080'
      DEBUG: 'false'
      TTL_SECONDS: '1800' # 30 minutes
      EVICTION_INTERVAL_MS: '1000' # 1 second